//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBCC.Authorizaion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NBCC.Authorizaion.Properties.SqlScript", typeof(SqlScript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRY
        ///
        ///	BEGIN TRANSACTION  
        ///
        ///		Declare @UserID INT
        ///		Declare @DefaultID INT
        ///
        ///		INSERT Secure.Users (UserName, Email)
        ///		VALUES (@UserName, @Email)
        ///
        ///		SET @UserID = SCOPE_IDENTITY()
        ///
        ///		SELECT @DefaultID = RoleID FROM Secure.Roles WHERE IsDefault = 1
        ///
        ///		INSERT INTO [Secure].[UserRoles]([UserID],[RoleID])
        ///		VALUES (@UserID, @DefaultID)
        ///
        ///		INSERT INTO Secure.Credentials (UserID, [Password], [Hash])
        ///		VALUES (@UserID, @Password, @Hash)
        ///
        ///	COMMIT TRANSACTION
        ///
        ///END TRY  
        ///BEGIN CATCH 
        ///  IF  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INSERT_User {
            get {
                return ResourceManager.GetString("INSERT_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select [hash],[password] from secure.Credentials c
        ///inner join secure.users u 
        ///on u.UserID = c.UserID
        ///where username=@userName and IsActive=1.
        /// </summary>
        internal static string SELECT_passwordByUserName {
            get {
                return ResourceManager.GetString("SELECT_passwordByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT RoleID, RoleName, IsDefault FROM Secure.Roles
        ///WHERE RoleID = @RoleID OR @RoleID IS NULL.
        /// </summary>
        internal static string SELECT_Roles {
            get {
                return ResourceManager.GetString("SELECT_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select u.UserID, u.UserName,r.roleid, r.rolename, r.isdefault
        ///from secure.roles r
        ///inner join secure.UserRoles ur on r.RoleID = ur.RoleID
        ///inner join secure.Users u on ur.UserID = u.UserID
        ///where username=@userName.
        /// </summary>
        internal static string SELECT_userByUserName {
            get {
                return ResourceManager.GetString("SELECT_userByUserName", resourceCulture);
            }
        }
    }
}
