//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBCC.Instructors.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NBCC.Instructors.Properties.SqlScript", typeof(SqlScript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [College].[Assignments]
        ///   SET IsArchived = 1
        /// WHERE [InstructorId] = @InstructorId
        /// 
        ///
        ///
        ///.
        /// </summary>
        internal static string ARCHIVE_Assignments {
            get {
                return ResourceManager.GetString("ARCHIVE_Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Staff.Instructors
        ///SET IsArchived = 1
        ///WHERE InstructorId = @InstructorId.
        /// </summary>
        internal static string ARCHIVE_Instructors {
            get {
                return ResourceManager.GetString("ARCHIVE_Instructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an automated message to inform you that a course assigned to you has been deleted..
        /// </summary>
        internal static string CourseDeletedMessage {
            get {
                return ResourceManager.GetString("CourseDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Deleted.
        /// </summary>
        internal static string CourseDeletedSubject {
            get {
                return ResourceManager.GetString("CourseDeletedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [College].[Assignments]
        ///           ([InstructorId],[CourseId])
        ///           
        ///     VALUES (@InstructorId,@CourseId)
        ///
        ///
        ///SELECT @@IDENTITY.
        /// </summary>
        internal static string INSERT_Assignments {
            get {
                return ResourceManager.GetString("INSERT_Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///INSERT INTO [Staff].[Instructors]
        ///           ([FirstName]
        ///           ,[LastName]
        ///           ,[Email])
        ///     VALUES
        ///           (@FirstName,
        ///           @LastName,
        ///           @Email)
        ///           
        ///SELECT @@IDENTITY.
        /// </summary>
        internal static string INSERT_Instructors {
            get {
                return ResourceManager.GetString("INSERT_Instructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.[AssignmentId]
        ///      ,c.[CourseId]
        ///      ,c.[InstructorId]
        ///	  ,CO.CourseId
        ///	  ,CO.CourseName
        ///	  ,i.InstructorId
        ///	  ,i.FirstName
        ///	  ,i.LastName
        ///	  ,i.Email
        ///  FROM [College].[Assignments] c
        ///  INNER JOIN College.Courses CO ON C.CourseId = CO.CourseId AND CO.IsArchived=0
        ///  INNER JOIN Staff.Instructors i on i.InstructorId = c.InstructorId and i.IsArchived=0
        ///  WHERE c.InstructorId = @InstructorId
        ///  AND c.IsArchived = 0.
        /// </summary>
        internal static string SELECT_Assignments {
            get {
                return ResourceManager.GetString("SELECT_Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT [InstructorId]
        ///      ,[FirstName]
        ///      ,[LastName]
        ///      ,[Email]
        ///  FROM [Staff].[Instructors]
        ///WHERE IsArchived = 0
        ///.
        /// </summary>
        internal static string SELECT_Instructors {
            get {
                return ResourceManager.GetString("SELECT_Instructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT i.InstructorId
        ///	  ,i.FirstName
        ///	  ,i.LastName
        ///	  ,i.Email
        ///  FROM [College].[Assignments] c
        ///  INNER JOIN College.Courses CO ON C.CourseId = CO.CourseId AND CO.IsArchived=0
        ///  INNER JOIN Staff.Instructors i on i.InstructorId = c.InstructorId and i.IsArchived=0
        ///  WHERE co.courseid = @CourseId
        ///  AND c.IsArchived = 0.
        /// </summary>
        internal static string SELECT_InstructorsByCourse {
            get {
                return ResourceManager.GetString("SELECT_InstructorsByCourse", resourceCulture);
            }
        }
    }
}
